import type { Metadata } from 'next'
import { Kalam } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/navbar'
import { Toaster } from 'react-hot-toast'

const kalam = Kalam({ subsets: ['latin'], weight: "400" })

export const metadata: Metadata = {
  title: 'Piclock',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={kalam.className}>
        <NavBar />
        {children}
        <Toaster />
        </body>
    </html>
  )
}
